---
- name: Example play
  hosts: system1
  become: true
  tasks:
    - name: copying a file
      ansible.builtin.copy:
        src: ./example.txt
        dest: /tmp/example.txt
        mode: "0644"

    - name: adding a user
      ansible.builtin.user:
        name: bob
        state: present
        uid: 1045

- name: Installing a latest version of postgres DB
  hosts: database
  become: true
  tasks:
    - name: Installing a postgres DB
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - postgresql
        - postgresql-server

    - name: Ensure postgres is started
      ansible.builtin.service:
        name: postgresql
        state: started


