---
- name: handler1
  hosts: example
  vars:
    httpd_conf_file: "/etc/httpd/conf/httpd.conf"
  tasks:
    - name: task1
      yum: 
        name: httpd 
        state: present
    - name:
      shell: "sed -i 's/Listen 80/Listen 81/g' {{ httpd_conf_file }}"
      #https://gist.github.com/TheSunMan/4008088
      become: true
      notify:
        - Restart httpd & firewall
        - Config firewalld

  handlers:
    - name: Restart httpd & firewall
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - httpd
        - firewalld
    - name: Config firewalld
      firewalld:
        port: 81/tcp
        state: enabled
        permanent: true
        immediate: true
