---
- name:
  hosts: localhost
  connection: local
  gather_facts: true
  force_handler: true
  tasks:
  - name: Install nginx on Ubuntu
    apt:
      name: nginx
      state: present
    when: ansible_distribution == "Ubuntu"
  - name: Install multiple packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - curl
      - git
  - name: Just force systemd to reread configs (2.4 and above)
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  
  handlers:
    - name: start service
      systemd:
        name: nginx
        state: restarted
        daemon_reload: true
        enabled: true
        masked: no


