---
- name: execute command on specified directory
  hosts: nis_system1
  become: true
  tasks:
    - name: Executing a basic command
      shell: ls -l
      args:
        chdir: /var/log/
      register: output

    - name:
      debug:
        var: output.stdout_lines

