---
- name: configuring a ssh between managed nodes
  hosts: system1, system2, system3
  vars:
    - ssh_user: root  #user at ssh client from which ssh initiate
    - user_home: /root  # user home directory to locate a generated ssh key
    - ssh_client: system2  # client system name where ssh initiate
  tasks:
    - name: Creating a ssh key for the user account
      user:
        name: "{{ ssh_user }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        #force: true  # to overrite the .ssh/id_rsa key
      when: inventory_hostname == ssh_client
    
    - name:
      fetch: #fetching from ssh_client ---> control node
        dest: "/ssh_keys/{{ ssh_client }}-{{ ssh_user }}-id_rsa.pub"
        src: "{{ user_home }}/.ssh/id_rsa.pub"
        flat: true
      when: inventory_hostname == ssh_client

    - name: Set authorized key taken from file # can be multiple ssh server
      ansible.posix.authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', '/ssh_keys/{{ ssh_client}}-{{ ssh_user }}-id_rsa.pub') }}"
      when: inventory_hostname != ssh_client  # run on all nodes expect ssh_client

