---
- name:
  hosts: system2
  tasks:
    - name:
      stat:
        path: /etc/httpd/conf/httpd.conf
      register: stat_facts

    - name:
      debug:
        msg: "file exist"
      when: stat_facts.stat.exists == true

    - name:
      debug:
        msg: "file not exist"
      when: stat_facts.stat.exists == false
